project/apps/cart/modules/autoship_order/urls.py
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path("jaautoship/index", views.AutoshipRequests.as_view(), name="autoship_requests"),
    path("jaautoship/manage", views.AutoshipRequests.as_view(), name="autoship_requests"),
    path("jaautoship/manage/edit/id/<int:autoship_id>", views.AutoshipRequestsConfigure.as_view(), name="autoship_requests_configure"),
    path("jaautoship/index/cancelnext/id/<int:autoship_id>", views.AutoshipRequests.as_view(), name="autoship_requests_cancel_next"),
    path("jaautoship/index/output/id/<int:autoship_id>", views.AutoshipRequests.as_view(), name="autoship_requests_optout"),
]

project/apps/cart/urls.py
from django.urls import path, re_path
from django.shortcuts import redirect
from . import views
from .views.base_view import BaseView

from .modules.urls import urlpatterns as modules_urls

app_name = "cart"
urlpatterns = [
    # path("import/<import_type>", views.ImportMagentoView.as_view(), name="import_magento"),
    # path("import/<import_type>/<migration_type>", views.ImportMagentoView.as_view(), name="import_magento_with_type"),

    path("favicon.ico", BaseView.file_renderer, name="favicon"),
    re_path('media/favicon/default/favicon.ico', lambda request: redirect('cart:favicon')),
    path("", views.Home.as_view(), name="home"),

    path("checkout/cart", views.CartView.as_view(), name="checkout_cart"),
    path("checkout/cart/<request_type>", views.CartView.as_view(), name="cart_update"),
    path("checkout/cart/<request_type>/<type_id>", views.CartView.as_view(), name="cart_add_delete"),
    path("onestepcheckout", views.CheckoutView.as_view(), name="checkout"),
    re_path(r'^onestepcheckout/index/(?P<submit_type>(saveOrder|is_valid_email|is_valid_referrer|addproduct|minusproduct|deleteproduct|save_shipping))',
            views.CheckoutView.as_view(), name="checkout_post"),
    path("checkout/onepage/success", views.CheckoutView().checkout_success, name="order_success"),

    path("customer/account/login", views.LoginView.as_view(), name="account_login"),
    path("customer/account/loginPost/", views.LoginView.as_view(), name="account_login_post"),
    path("customer/account/forgotpassword", views.Home.as_view(), name="account_forgot_password"),
    path("customer/logout", views.LogoutView.as_view(), name="account_logout"),

    path("customer/account", views.AccountDashboardView.as_view(), name="account_dashboard"),
    path("customer/account/edit", views.AccountEditView.as_view(), name="account_information"),
    path("customer/account/edit/changepass", views.AccountEditView.as_view(), name="account_change_pass"),
    path("customer/address", views.AccountAddressView.as_view(), name="account_address"),
    path("customer/address/add", views.AccountAddressAddView.as_view(), name="account_address_add"),
    path("customer/address/edit/id/<int:pk>", views.AccountAddressEditView.as_view(), name="account_address_edit"),
    path("customer/address/delete/id/<int:pk>", views.AccountAddressDeleteView.as_view(), name="account_address_delete"),

    path("sales/order/history", views.AccountOrderListView.as_view(), name="account_orders"),
    path("sales/order/view/order_id/<int:pk>", views.AccountOrderView.as_view(), name="account_order_view"),
    path("sales/order/print/order_id/<int:pk>", views.AccountOrderView.as_view(), name="account_order_print"),
    path("sales/order/invoice/order_id/<int:pk>", views.AccountOrderInvoiceView.as_view(), name="account_order_invoice_list"),
    path("sales/order/shipment/order_id/<int:pk>", views.AccountOrderShipmentView.as_view(), name="account_order_shipment_list"),
    path("sales/order/creditmemo/order_id/<int:pk>", views.AccountOrderRefundsView.as_view(), name="account_order_refund_list"),

    # path("recurringandrentalpayments/customer", views.AccountDashboardView.as_view(), name="account_subscriptions"),
    path("authnetcim/manage/", views.Home.as_view(), name="account_manage_cards"),
    # path("jaautoship/manage", views.AccountDashboardView.as_view(), name="account_autoships"),

    # path("sales/order/view/<order_id>", views.Home.as_view(), name="view_order_details"),
    # path("sales/invoice/view/<order_id>", views.Home.as_view(), name="view_invoice_details"),
    # path("sales/ship/view/<order_id>", views.Home.as_view(), name="view_shipment_details"),
]

urlpatterns += modules_urls

urlpatterns += [
    re_path(r'^jamemberrefer/setsession/(?P<submit_type>(set|unset))', views.MemberSessionView.as_view(), name="member_session"),
    re_path(r'^(?P<cat_prod_url_path>[\w\d\/\-\.html]+)$', views.CategoryOrProductOrReferrerSelector.as_view(),
            name="cat_prod_ref"),
]

project/core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


admin.site.index_template = 'admin/admin_index.html'
admin.site.app_index_template = 'admin/admin_index.html'

urlpatterns = []

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [

    path(settings.ADMIN_URL_NAME + "/", admin.site.urls),
    # path('accounts/', include(('allauth.urls', "allauth"), namespace="accounts"), name="accounts", ),
    path('accounts/', include('django.contrib.auth.urls'), name="accounts", ),
    path('summernote/', include('django_summernote.urls')),
    path("", include("apps.cart.urls")),

]

project/apps/cart/modules/autoship_order/views/autoship_requests.py
import datetime
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import ListView
from ....utils import helper
from ....views.account.base_account_view import BaseAccountView
from ..models import AutoshipRequest


class AutoshipRequests(BaseAccountView, ListView):
    model = AutoshipRequest
    template_name = 'cart/modules/autoship_order/templates/frontend/pages/list.html'
    context_object_name = 'autoship_requests'  # Default: object_list
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_common_context_data(**kwargs))
        context['html_extra']['page_title'] = "Autoship Requests"

        return context

    def get_queryset(self):
        super_q = super().get_queryset()
        customer = self.get_customer_extra()
        if customer:
            queryset = super_q.filter(customer=self.get_customer_extra(), status__in=[1]).order_by('created_at').all()
        else:
            queryset = super_q.none()

        return queryset


class AutoshipRequestsConfigure(BaseAccountView):
    model = AutoshipRequest
    template = 'cart/modules/autoship_order/templates/frontend/pages/configure.html'

    def get(self, request, *args, **kwargs):
        logged_in = self.customer_login_required()
        if not isinstance(logged_in, bool) or not logged_in:
            return redirect('cart:account_login')

        autoship_id = kwargs['autoship_id'] if 'autoship_id' in kwargs else False
        if autoship_id and isinstance(autoship_id, int):
            queryset = self.get_queryset(autoship_id)
            if queryset.exists():
                autoship = queryset.get()
                # autoship.get_next_order_placing_time()
                autoship_request = autoship.get_autoship_request_full()

                if not autoship_request['orderable_products']:
                    messages.add_message(request, messages.ERROR, "No products found to configure!")
                else:
                    context = self.get_context_data(queryset)
                    context['ar'] = autoship_request

                    return render(request, self.template, context)
            else:
                messages.add_message(request, messages.ERROR, "Illegal ID submitted in the request!")
        else:
            messages.add_message(request, messages.ERROR, "Illegal ID submitted in the request!")

        return redirect('cart:autoship_requests')

    def post(self, request, *args, **kwargs):
        logged_in = self.customer_login_required()
        if not isinstance(logged_in, bool) or not logged_in:
            return redirect('cart:account_login')

        error = False
        autoship_id = kwargs['autoship_id'] if 'autoship_id' in kwargs else False

        if autoship_id and isinstance(autoship_id, int):
            queryset = self.get_queryset(autoship_id)
            if queryset.exists():
                autoship_request = queryset.get().get_autoship_request_full()

                if request.POST:
                    statues = helper.get_html_input_dict(request.POST, 'autoshipProd')
                    quantities = helper.get_html_input_dict(request.POST, 'autoshipProdQty')

                    enabled_prods = {}
                    enabled_prod_ids = []

                    if statues and isinstance(statues, dict):
                        for prod_id, enabled in statues.items():
                            if int(enabled):
                                qty = int(quantities[prod_id]) if prod_id in quantities and quantities[prod_id]\
                                    .isnumeric() else False
                                if qty:
                                    enabled_prod_ids.append(int(prod_id))
                                    enabled_prods[int(prod_id)] = qty

                        if enabled_prods:
                            removable_prods = list(set(autoship_request['orderable_products'].keys()) - set(enabled_prod_ids))
                            for prod_id, prod in autoship_request['orderable_products'].items():
                                if prod_id in enabled_prod_ids:
                                    autoship_request['orderable_products'][prod_id].quantity = enabled_prods[prod_id]
                                    autoship_request['orderable_products'][prod_id].save()

                                if prod_id in removable_prods:
                                    autoship_request['orderable_products'][prod_id].status = 2
                                    autoship_request['orderable_products'][prod_id].save()

                            messages.add_message(request, messages.SUCCESS, "Successfully saved the changes")
                        else:
                            error = True
                            messages.add_message(request, messages.ERROR, "You must have at least 1 enabled item "
                                                                          "with a minimum of 1 quantity to be shipped "
                                                                          "with this Auto Shipment request")
                    else:
                        error = True
                        messages.add_message(request, messages.ERROR, "You must have at least 1 item to be shipped "
                                                                      "with this Auto Shipment request")

                    if error:
                        context = self.get_context_data(queryset)
                        context['ar'] = autoship_request

                        if quantities:
                            for prod_id, qty in quantities.items():
                                context['ar']['orderable_products'][int(prod_id)].quantity = float(qty)

                        return render(request, self.template, context)

                #     { % if ar_post %}
                #     $autoshipProd['status'] = isset($autoshipRequestPost['autoshipProd'][$autoshipProd[
                #         'autoship_product_id']]) ? 1: 0;
                #     $autoshipProd['qty'] = isset($autoshipRequestPost['autoshipProdQty'][$autoshipProd[
                #         'autoship_product_id']]) ? $autoshipRequestPost['autoshipProdQty'][$autoshipProd[
                #         'autoship_product_id']]: $autoshipProd['qty'];
                # }
                # ? >

        return self.get(request, *args, **kwargs)

    def get_context_data(self, queryset, **kwargs):
        context = {}
        context.update(self.get_common_context_data(**kwargs))
        context['html_extra']['page_title'] = "Update My Autoship Request Products"

        if queryset.exists():
            context['ar'] = queryset.get().get_autoship_request_full()

        return context

    def get_queryset(self, autoship_id):
        customer = self.get_customer_extra()
        if customer:
            queryset = self.model.objects.filter(customer=self.get_customer_extra(), status__in=[1], id=autoship_id)
        else:
            queryset = self.model.objects.none()

        return queryset

project/apps/cart/modules/autoship_order/templates/frontend/pages/configure.html
{% extends 'frontend/pages/accounts/base.html' %}
{% load static %}

{% block content %}
    <style type="text/css">
        .autoship_edit table {
            width: 100%;
        }
        .fieldset .legend {
            font-size: 16px;
            margin: 0 0 20px;
            text-transform: uppercase;
        }
        .autoship_edit table tr.row_content {
            border: 1px solid #d0d0d0;
        }
        .autoship_edit table td.row_title,
        .autoship_edit table th.row_title {
            background-color: #e6e6e6;
            padding: 10px;
            width: 35%;
            color: black;
        }
        .autoship_edit table .row_body {
            color: black;
            padding: 0px 10px;
            padding-top: 10px;
            padding-bottom: 10px;
        }
        .fieldset + .fieldset {
            margin-top: 35px;
        }
        .buttons-set {
            clear: both;
            margin: 1em 0 0;
            padding: 8px 0 0;
            text-align: right;
            margin-top: 40px;
        }
        .buttons-set .back-link {
            float: left;
            margin: 0;
        }
        .buttons-set button.button {
            float: right;
            margin-left: 5px;
        }
        .orderedProducts_inner td {
            vertical-align: middle;
        }
        .orderedProducts_inner .autoshipProdName {
            margin-bottom: 10px;
        }
    </style>
    <div class="dashboard">
        <div class="page-title">
            <h1>{{ html_extra.page_title }}</h1>
        </div>
        <div class="box-account box-address-edit">
            <div class="row">
                <div class="col">
                    <div class="card mb-3">
                        <div class="card-body">
                            <form action="" method="post" id="form-validate" class="autoship_edit_form">
                                {% csrf_token %}
                                <div class="autoship_edit">
                                    <div class="fieldset">
                                        <h2 class="legend">Order Information</h2>
                                        <table>
                                            <tr class="row_content">
                                                <td class="row_title">Order #</td>
                                                <td class="row_body">
                                                    <a href="{% url 'cart:account_order_view' ar.parent_order.id %}" target="_blank">{{ ar.parent_order.get_order_id }}</a>
                                                </td>
                                            </tr>
                                            <tr class="row_content">
                                                <td class="row_title">Order Created On</td>
                                                <td class="row_body">
                                                    <div class="form-control-static">
                                                        <strong>{{ ar.parent_order.created_at|date:"m/d/Y" }}</strong>
                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                    <div class="fieldset">
                                        <h2 class="legend">AutoShip Request Information</h2>
                                        <table>
                                            <tr class="row_content">
                                                <td class="row_title">AutoShip Enabled</td>
                                                <td class="row_body">
                                                    <div class="form-control-static"><strong>{% if ar.is_enabled %}Yes{% else %}No{% endif %}</strong></div>
                                                </td>
                                            </tr>
                                            <tr class="row_content">
                                                <td class="row_title">AutoShip Interval</td>
                                                <td class="row_body">
                                                    <div class="form-control-static"><strong>{{ ar.autoship_request.interval_period_number }} {{ ar.autoship_request.interval_period_type }}</strong></div>
                                                </td>
                                            </tr>
                                            <tr class="row_content">
                                                <td class="row_title">Next Order will be Placed On</td>
                                                <td class="row_body">
                                                    <div class="form-control-static"><strong>{{ ar.last_attempt.next_order_placing_time|date:"m/d/Y" }}</strong></div>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                    <div class="fieldset">
                                        <div class="orderedProducts">
                                            <h2 class="legend">Ordered Products</h2>
                                            <div class="orderedProducts_inner">
                                                <table>
                                                    <thead>
                                                    <tr class="row_content">
                                                        <th class="row_title" style="width: 5%;max-width: 50px;">Sl.</th><th class="row_title">Product Name</th><th class="row_title">Enabled</th><th class="row_title">Quantity</th>
                                                    </tr>
                                                    </thead>
                                                    <tbody>
                                                    {% if ar.orderable_products %}
                                                    {% for arp_key, arp in ar.orderable_products.items %}
                                                        {% if arp.status < 3 and arp.status > 0 %}
                                                            <tr class="row_content">
                                                                <td class="row_body" style="width: 5%;max-width: 50px;"><span>{{ forloop.counter }}</span></td>
                                                                <td class="row_body" style="width: 60%;">
                                                                    <label class="control-label" for="autoshipProd_{{ arp.product_id }}">
                                                                        <div class="autoshipProdName">{{ arp.product.name }}</div>
                                                                        <div class="autoshipProdSku"><strong>Product SKU:</strong> {{ arp.product.sku }}</div>
                                                                    </label>
                                                                </td>
                                                                <td class="row_body" style="width: 15%;">
                                                                    <input type="checkbox" class="" id="autoshipProd_{{ arp.product_id }}" name="autoshipProd[{{ arp.product_id }}]" value="1"
                                                                        {% if arp.status == 1 %}checked{% endif %}
                                                                    />
                                                                    <input type="hidden" name="autoshipProdHidden[{{ arp.product_id }}]" value="1" />
                                                                </td>
                                                                <td class="row_body" style="width: 20%;">
                                                                    <input type="text" class="form-control" id="autoshipProdQty_{{ arp.product_id }}"
                                                                           name="autoshipProdQty[{{ arp.product_id }}]" value="{{ arp.quantity|floatformat:0 }}" />
                                                                </td>
                                                            </tr>
                                                        {% endif %}
                                                    {% endfor %}
                                                    {% else %}
                                                        <tr class="row_content"><td class="row_body" colspan="5">No product found</td></tr>
                                                    {% endif %}
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                <div class="buttons-set">
                                    <p class="back-link"><a href="{% url 'cart:autoship_requests' %}"><small>« </small>Back</a></p>
                                    <button type="submit" title="Save" class="button"><span><span>Save</span></span></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

project/apps/cart/modules/autoship_order/templates/frontend/pages/list.html
{% extends 'frontend/pages/accounts/base.html' %}
{% load static %}


{% block head_style_block %}
{#    {{ block.super }}#}
    {% include 'frontend/parts/page/accounts/base/style.html' %}
{% endblock %}

{% block content %}
    <style type="text/css">
        .bsbtn {
            display: inline-block;
            margin-bottom: 0;
            font-weight: normal;
            text-align: center;
            vertical-align: middle;
            -ms-touch-action: manipulation;
            touch-action: manipulation;
            cursor: pointer;
            background-image: none;
            border: 1px solid transparent;
            white-space: nowrap;
            padding: 6px 12px;
            font-size: 14px;
            line-height: 1.42857143;
            border-radius: 0;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }
        .bsbtn-success {
            color: #ffffff;
            background-color: #00a388;
            border-color: #008a73;
        }
        .bsbtn-primary {
            color: #ffffff;
            background-color: #d02660;
            border-color: #ba2256;
        }
        .bsbtn-xs, .bsbtn-group-xs > .bsbtn {
            padding: 1px 5px;
            font-size: 12px;
            line-height: 1.5;
            border-radius: 0;
        }
        a.bsbtn {
            text-decoration: none;
        }
        .autoship_requests .action_item {
            margin-bottom: 5px;
            text-align: left;
        }
        .autoship_requests .action_item {
            margin-bottom: 5px;
            text-align: left;
        }
        .autoship_requests a.bsbtn {
            color: white;
        }
    </style>
    <div class="dashboard">
        <div class="page-title">
            <h1>My {{ html_extra.page_title }}</h1>
        </div>
        <div class="box-account box-recent autoship_requests">
            <div class="table-responsive">
                <table class="data-table table" id="my-orders-table">
                    <thead>
                        <tr class="first last">
                            <th>Order #</th>
                            <th>Order Date</th>
                            <th><span class="nobr">Auto Ship Interval</span></th>
                            <th><span class="nobr">Next Shipment Date</span></th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if autoship_requests.count > 0 %}
                        {% for ar in autoship_requests %}
                            <tr class="">
                                <td><a href="{% url 'cart:account_order_view' ar.parent_order_id %}" target="_blank">{{ ar.parent_order.get_order_id }}</a></td>
                                <td><span class="nobr">{{ ar.parent_order.created_at|date:"m/d/Y" }}</span></td>
                                <td>{{ ar.interval_period_number }} {{ ar.interval_period_type }}</td>
                                <td>{{ ar.get_last_autoship_request_attempt.next_order_placing_time|date:"m/d/Y" }}</td>
                                <td class="a-center last">
                                    <span class="nobr">
                                        <div class="action_item">
                                            <a href="{% url 'cart:autoship_requests_configure' ar.id %}" class="configAutship bsbtn bsbtn-success bsbtn-xs">Config Products</a>
                                        </div>
                                        <div class="action_item">
                                            <a href="{% url 'cart:autoship_requests_cancel_next' ar.id %}" class="cancelAutship bsbtn bsbtn-primary bsbtn-xs" onclick="return confirm('Are you sure, you want cancel the next shipment? This action cannot be undone.')">Cancel Next Shipment</a>
                                        </div>
                                        <div class="action_item">
                                            <a href="{% url 'cart:autoship_requests_optout' ar.id %}" class="unsubAutship bsbtn bsbtn-primary bsbtn-xs" onclick="return confirm('Are you sure, you want unsbscribe Auto Shipment Request for this order? This action cannot be undone.')">Opt Out</a>
                                        </div>
                                    </span>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="5">No Autoship Request found!</td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}