project/apps/cart/modules/autoship_order/urls.py
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path("jaautoship/index", views.AutoshipRequests.as_view(), name="autoship_requests"),
    path("jaautoship/manage", views.AutoshipRequests.as_view(), name="autoship_requests"),
    path("jaautoship/manage/edit/id/<int:autoship_id>", views.AutoshipRequestsConfigure.as_view(), name="autoship_requests_configure"),
    path("jaautoship/index/cancelnext/id/<int:autoship_id>", views.AutoshipRequests.as_view(), name="autoship_requests_cancel_next"),
    path("jaautoship/index/output/id/<int:autoship_id>", views.AutoshipRequests.as_view(), name="autoship_requests_optout"),
]

project/apps/cart/modules/urls.py
from .module_loader import import_sub_modules

urlpatterns = import_sub_modules('urls', urlpatterns=[])

project/apps/cart/urls.py
from django.urls import path, re_path
from django.shortcuts import redirect
from . import views
from .views.base_view import BaseView

from .modules.urls import urlpatterns as modules_urls

app_name = "cart"
urlpatterns = [
    # path("import/<import_type>", views.ImportMagentoView.as_view(), name="import_magento"),
    # path("import/<import_type>/<migration_type>", views.ImportMagentoView.as_view(), name="import_magento_with_type"),

    path("favicon.ico", BaseView.file_renderer, name="favicon"),
    re_path('media/favicon/default/favicon.ico', lambda request: redirect('cart:favicon')),
    path("", views.Home.as_view(), name="home"),

    path("checkout/cart", views.CartView.as_view(), name="checkout_cart"),
    path("checkout/cart/<request_type>", views.CartView.as_view(), name="cart_update"),
    path("checkout/cart/<request_type>/<type_id>", views.CartView.as_view(), name="cart_add_delete"),
    path("onestepcheckout", views.CheckoutView.as_view(), name="checkout"),
    re_path(r'^onestepcheckout/index/(?P<submit_type>(saveOrder|is_valid_email|is_valid_referrer|addproduct|minusproduct|deleteproduct|save_shipping))',
            views.CheckoutView.as_view(), name="checkout_post"),
    path("checkout/onepage/success", views.CheckoutView().checkout_success, name="order_success"),

    path("customer/account/login", views.LoginView.as_view(), name="account_login"),
    path("customer/account/loginPost/", views.LoginView.as_view(), name="account_login_post"),
    path("customer/account/forgotpassword", views.Home.as_view(), name="account_forgot_password"),
    path("customer/logout", views.LogoutView.as_view(), name="account_logout"),

    path("customer/account", views.AccountDashboardView.as_view(), name="account_dashboard"),
    path("customer/account/edit", views.AccountEditView.as_view(), name="account_information"),
    path("customer/account/edit/changepass", views.AccountEditView.as_view(), name="account_change_pass"),
    path("customer/address", views.AccountAddressView.as_view(), name="account_address"),
    path("customer/address/add", views.AccountAddressAddView.as_view(), name="account_address_add"),
    path("customer/address/edit/id/<int:pk>", views.AccountAddressEditView.as_view(), name="account_address_edit"),
    path("customer/address/delete/id/<int:pk>", views.AccountAddressDeleteView.as_view(), name="account_address_delete"),

    path("sales/order/history", views.AccountOrderListView.as_view(), name="account_orders"),
    path("sales/order/view/order_id/<int:pk>", views.AccountOrderView.as_view(), name="account_order_view"),
    path("sales/order/print/order_id/<int:pk>", views.AccountOrderView.as_view(), name="account_order_print"),
    path("sales/order/invoice/order_id/<int:pk>", views.AccountOrderInvoiceView.as_view(), name="account_order_invoice_list"),
    path("sales/order/shipment/order_id/<int:pk>", views.AccountOrderShipmentView.as_view(), name="account_order_shipment_list"),
    path("sales/order/creditmemo/order_id/<int:pk>", views.AccountOrderRefundsView.as_view(), name="account_order_refund_list"),

    # path("recurringandrentalpayments/customer", views.AccountDashboardView.as_view(), name="account_subscriptions"),
    path("authnetcim/manage/", views.Home.as_view(), name="account_manage_cards"),
    # path("jaautoship/manage", views.AccountDashboardView.as_view(), name="account_autoships"),

    # path("sales/order/view/<order_id>", views.Home.as_view(), name="view_order_details"),
    # path("sales/invoice/view/<order_id>", views.Home.as_view(), name="view_invoice_details"),
    # path("sales/ship/view/<order_id>", views.Home.as_view(), name="view_shipment_details"),
]

urlpatterns += modules_urls

urlpatterns += [
    re_path(r'^jamemberrefer/setsession/(?P<submit_type>(set|unset))', views.MemberSessionView.as_view(), name="member_session"),
    re_path(r'^(?P<cat_prod_url_path>[\w\d\/\-\.html]+)$', views.CategoryOrProductOrReferrerSelector.as_view(),
            name="cat_prod_ref"),
]

project/core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


admin.site.index_template = 'admin/admin_index.html'
admin.site.app_index_template = 'admin/admin_index.html'

urlpatterns = []

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [

    path(settings.ADMIN_URL_NAME + "/", admin.site.urls),
    # path('accounts/', include(('allauth.urls', "allauth"), namespace="accounts"), name="accounts", ),
    path('accounts/', include('django.contrib.auth.urls'), name="accounts", ),
    path('summernote/', include('django_summernote.urls')),
    path("", include("apps.cart.urls")),

]

project/apps/cart/models/authnetcim_cards.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from ..utils import static


class AuthnetcimCards(models.Model):
    id = models.AutoField(primary_key=True)
    # customer = models.ForeignKey(
    #     User,
    #     on_delete=models.CASCADE,
    #     db_index=True,
    #     blank=True,
    #     null=True
    # )
    # customer_extra = models.ForeignKey(
    #     'CustomerExtra',
    #     on_delete=models.CASCADE,
    #     db_index=True,
    #     blank=True,
    #     null=True
    # )
    authnetcim_customer = models.ForeignKey('AuthnetcimCustomers', on_delete=models.CASCADE, blank=True, null=False)
    authnetcim_payment_profile_id = models.CharField(max_length=100, blank=False, null=False)
    card_owner = models.CharField(max_length=200, blank=True, null=True)
    card_type = models.CharField(max_length=20, blank=True, null=True, choices=static.CARD_TYPES)
    card_last4 = models.IntegerField(blank=False, null=False)
    card_exp_month = models.IntegerField(blank=False, null=False)
    card_exp_year = models.IntegerField(blank=False, null=False)
    is_disabled = models.BooleanField(blank=True, null=False, default=False)

    created_at = models.DateTimeField(auto_now_add=True, blank=True)

    class Meta:
        ordering = ['authnetcim_payment_profile_id']
        unique_together = ('authnetcim_customer_id', 'authnetcim_payment_profile_id')

    def __str__(self):
        return 'Customer Profile: {} - Card# {} - xxxxx-{} - Exp: {}/{}'.format(
            self.authnetcim_customer.customer_profile_id, self.card_type, self.card_last4, self.card_exp_month, self.card_exp_year)

project/apps/cart/models/authnetcim_cards_transactions.py
from django.db import models


class AuthnetcimCardsTransactions(models.Model):
    id = models.AutoField(primary_key=True)

    authnetcim_card = models.ForeignKey('AuthnetcimCards', on_delete=models.CASCADE, blank=True, null=False)
    payment_transaction = models.ForeignKey('PaymentTransaction', on_delete=models.CASCADE, blank=True, null=False)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)

project/apps/cart/models/authnetcim_customers.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from ..utils import static


class AuthnetcimCustomers(models.Model):
    id = models.AutoField(primary_key=True)

    customer = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True, null=True)
    tbl_member = models.ForeignKey('TblMember', on_delete=models.CASCADE, blank=True, null=True)

    customer_profile_id = models.IntegerField(blank=False, null=False, unique=True)

    created_at = models.DateTimeField(auto_now_add=True, blank=True)

    class Meta:
        ordering = ['customer_profile_id']
        # unique_together = ('customer_profile_id', 'customer_id', 'tbl_member_id')

    def __str__(self):
        return 'Authnet Customer Profile ID: {} - for {}'.format(
            self.customer_profile_id,
            (self.tbl_member.get_full_name() if not self.customer else self.customer.get_full_name()))

    def get_payment_objects(self):
        import datetime, calendar
        from datetime import timedelta

        cards = {}
        cards_q = self.authnetcimcards_set.filter(is_disabled=False)
        if cards_q.exists():
            for card in cards_q.all():
                _, last_day = calendar.monthrange(card.card_exp_year, card.card_exp_month)
                date_string = "{}/{}/{} {}:{}".format(card.card_exp_year, card.card_exp_month, last_day, 23, 59)
                date_time_obj = datetime.datetime.strptime(date_string, "%y/%m/%d %H:%M")
                if date_time_obj > datetime.datetime.now() + timedelta(minutes=30):
                    cards[card.id] = {
                        'title': 'xxxx-{} - Exp: {}/{}'.format(card.card_last4, card.card_exp_month,
                                                               card.card_exp_year),
                        'payment_profile_id': card.authnetcim_payment_profile_id
                    }

        return cards

project/apps/cart/models/category_product.py
from django.db import models
from django.utils import timezone

from .product import Product
from .category import Category


class CategoryProduct(models.Model):
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        db_index=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
    )
    order = models.IntegerField(blank=True, null=True, default=0)

    # created_at = models.DateTimeField(auto_now_add=True, blank=True)
    # updated_at = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        verbose_name_plural = 'Product Categories'

        index_together = ['category', 'product']

    def __str__(self):
        return '{} linked with {}'.format(self.product, self.category)

project/apps/cart/models/credit_memo_item.py
from django.db import models

from ..utils.static import PRODUCT_TYPE_CHOICES


class CreditMemoItem(models.Model):
    id = models.AutoField(primary_key=True)
    credit_memo = models.ForeignKey(
        'CreditMemo',
        on_delete=models.CASCADE,
        db_index=True,
    )
    product = models.ForeignKey(
        'Product',
        on_delete=models.CASCADE,
        db_index=True,
        null=True,
    )
    product_type = models.CharField(max_length=255, db_index=True, choices=PRODUCT_TYPE_CHOICES, default='simple',
                                    blank=True, null=True)
    sku = models.CharField(max_length=100, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    price = models.DecimalField(max_digits=15, decimal_places=4, blank=True, default=0, db_index=True)

    quantity = models.DecimalField(max_digits=15, decimal_places=2, blank=True, default=1, db_index=True)

    option = models.IntegerField(blank=True, null=True)
    option_title = models.CharField(max_length=255, blank=True, null=True)
    option_sku = models.CharField(max_length=255, blank=True, null=True)

    tax_percent = models.DecimalField(max_digits=15, decimal_places=2, blank=True, default=0, db_index=True)
    tax_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, default=0, db_index=True)

    discount_percent = models.DecimalField(max_digits=15, decimal_places=2, blank=True, default=0, db_index=True)
    discount_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, default=0, db_index=True)

    amount_refunded = models.DecimalField(max_digits=15, decimal_places=2, blank=True, default=0, db_index=True)

    currency = models.CharField(max_length=6, blank=True, null=True)
    row_subtotal = models.DecimalField(max_digits=15, decimal_places=4, blank=True, default=0, db_index=True)
    row_total = models.DecimalField(max_digits=15, decimal_places=4, blank=True, default=0, db_index=True)

    is_free_product = models.BooleanField(blank=True, null=False, default=False)

    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        verbose_name_plural = 'Credit Memo Items'
        ordering = ['-created_at']

    def __str__(self):
        return 'Credit Memo Item #{} for Credit Memo: {}'.format(self.sku, self.credit_memo.get_credit_memo_id())

    def get_row_subtotal(self):
        subtotal = float(self.row_subtotal)
        if subtotal <= 0:
            subtotal = float(self.price) * float(self.quantity)

        return subtotal

    def get_attributes(self):
        attrs = {
            'sku': {'title': 'SKU', 'value': self.sku + ("-"+self.option_sku if self.option_sku else '')},
            # 'option_sku': {'title': 'Option SKU', 'value': self.option_sku},
        }
        if self.option_title:
            attrs['option_title'] = {'title': 'Size', 'value': self.option_title}

        return attrs

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None, external_use=False):

        super().save(force_insert, force_update, using, update_fields)

    def delete(self, using=None, keep_parents=False):

        super().delete(using=None, keep_parents=False)

project/apps/cart/models/invoice_item.py
from django.db import models

from ..utils.static import PRODUCT_TYPE_CHOICES


class InvoiceItem(models.Model):
    id = models.AutoField(primary_key=True)
    invoice = models.ForeignKey(
        'Invoice',
        on_delete=models.CASCADE,
        db_index=True,
    )
    product = models.ForeignKey(
        'Product',
        on_delete=models.CASCADE,
        db_index=True,
        null=True,
    )
    order_item = models.ForeignKey(
        'OrderItem',
        on_delete=models.CASCADE,
        db_index=True,
        null=True,
    )
    product_type = models.CharField(max_length=255, db_index=True, choices=PRODUCT_TYPE_CHOICES, default='simple',
                                    blank=True, null=True)
    sku = models.CharField(max_length=100, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    price = models.DecimalField(max_digits=15, decimal_places=4, blank=True, default=0, db_index=True)

    quantity = models.DecimalField(max_digits=15, decimal_places=2, blank=True, default=1, db_index=True)

    option = models.IntegerField(blank=True, null=True)
    option_title = models.CharField(max_length=255, blank=True, null=True)
    option_sku = models.CharField(max_length=255, blank=True, null=True)

    tax_percent = models.DecimalField(max_digits=15, decimal_places=2, blank=True, default=0, db_index=True)
    tax_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, default=0, db_index=True)

    discount_percent = models.DecimalField(max_digits=15, decimal_places=2, blank=True, default=0, db_index=True)
    discount_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, default=0, db_index=True)

    amount_refunded = models.DecimalField(max_digits=15, decimal_places=2, blank=True, default=0, db_index=True)

    currency = models.CharField(max_length=6, blank=True, null=True)
    row_subtotal = models.DecimalField(max_digits=15, decimal_places=4, blank=True, default=0, db_index=True)
    row_total = models.DecimalField(max_digits=15, decimal_places=4, blank=True, default=0, db_index=True)

    is_free_product = models.BooleanField(blank=True, null=False, default=False)

    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        verbose_name_plural = 'Invoice Items'
        ordering = ['-created_at']

    def __str__(self):
        return 'Invoice Item #{} for Invoice: {}'.format(self.sku, self.invoice.get_invoice_id())

    def get_row_subtotal(self):
        subtotal = float(self.row_subtotal)
        if subtotal <= 0:
            subtotal = float(self.price) * float(self.quantity)

        return subtotal

    def get_attributes(self):
        attrs = {
            'sku': {'title': 'SKU', 'value': self.sku + ("-"+self.option_sku if self.option_sku else '')},
            # 'option_sku': {'title': 'Option SKU', 'value': self.option_sku},
        }
        if self.option_title:
            attrs['option_title'] = {'title': 'Size', 'value': self.option_title}

        return attrs

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None, external_use=False):

        super().save(force_insert, force_update, using, update_fields)

    def delete(self, using=None, keep_parents=False):

        super().delete(using=None, keep_parents=False)

project/apps/cart/templates/frontend/pages/accounts/address_list.html
{% extends 'frontend/pages/accounts/base.html' %}
{% load static %}


{% block before_body_end %}
<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery('.address_links .remove').click(function () {
            if(confirm("Are you sure you want to delete this address?")) {
                return true
            }
            return false
        })
    })
</script>
{% endblock %}

{% block head_style_block %}
{#    {{ block.super }}#}
    {% include 'frontend/parts/page/accounts/base/style.html' %}
{% endblock %}

{% block content %}
    <div class="dashboard">
        <style type="text/css">
            .additional_addresses {margin-top: 15px;}
            .address_links {}
            .address_links a { margin-right: 10px; }
            .address_links .edit { color: #08c; }
            .address_links .remove { color: darkred; margin-left: 10px;}
            .address_links .separator { color: gainsboro; }
        </style>
        <div class="page-title">
            <h1>Address Book</h1>
        </div>
        <div class="box-account box-address">
            <div class="row">
                <div class="col">
{#                    <h4 class="font-weight-bold">Default Addresses</h4>#}
                    {% include 'frontend/pages/accounts/parts/default_address.html' with default_billing_address=default_billing_address default_shipping_address=default_shipping_address %}
                </div>
            </div>
            <div class="row">
                <div class="col-12 additional_addresses">
                    <h4 class="font-weight-bold">Additional Address Entries</h4>
                    {% if not addresses %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <p>You have no other address entries in your address book.</p>
                        </div>
                    </div>
                    {% else %}
                        <div class="row">
                            {% for address in addresses %}
                            <div class="col-md-6">
                                <div class="card border-light mb-3 address">
                                    <div class="card-body">
                                        {% include 'frontend/pages/accounts/parts/address_view.html' with address=address %}
                                        <br><br>
                                        <div class="address_links">
                                            <a class="edit" href="{% url 'cart:account_address_edit' address.id %}">Edit Address</a>
                                            <span class="separator">|</span>
                                            <a class="remove" href="{% url 'cart:account_address_delete' address.id %}">Delete Address</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <div class="card border-light mb-3">
                        <div class="card-body">
                            <p><a class="btn btn-success" href="{% url 'cart:account_address_add' %}">Add new address</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

project/apps/cart/templates/frontend/pages/accounts/dashboard.html
{% extends 'frontend/pages/accounts/base.html' %}
{% load static %}


{% block head_style_block %}
{#    {{ block.super }}#}
    {% include 'frontend/parts/page/accounts/base/style.html' %}
{% endblock %}

{% block content %}
    <div class="dashboard">
        <div class="page-title">
            <h1>My Dashboard</h1>
        </div>
{#        <div class="welcome-msg">#}
{#            <p class="hello"><strong>Hello, Mainul Hasan!</strong></p>#}
{#            <p>From your My Account Dashboard you have the ability to view a snapshot of your recent account activity#}
{#                and update your account information. Select a link below to view or edit information.</p>#}
{#        </div>#}
        <div class="box-account box-info">
            <div class="box-head">
                <h3>Account Information</h3>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="card bg-light mb-3">
                        <div class="card-header">
                            <h4>Contact Information</h4>
                            <a href="{% url 'cart:account_information' %}">Edit</a>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ customer_extra.get_customer.get_full_name }}</h5>
                            <p class="card-text">
                                {{ customer_extra.get_customer.email }}<br>
                                <a href="{% url 'cart:account_information' %}">Change Password</a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="card bg-light mb-3">
                        <div class="card-header">
                            <h4>Newsletters</h4>
                            <a href="{% url 'cart:account_information' %}">Edit</a>
                        </div>
                        <div class="card-body">
                            <p>You are currently subscribed to 'General Subscription'. </p>
                        </div>
                    </div>
                </div>
            </div>
{#            <div class="row">#}
{#                <div class="col">#}
{#                    <div class="card bg-light mb-3">#}
{#                        <div class="card-header">#}
{#                            <h4>Address Book</h4>#}
{#                            <a href="{% url 'cart:account_address' %}">Manage Addresses</a>#}
{#                        </div>#}
{#                        <div class="card-body">#}
{#                            {% include 'frontend/pages/accounts/parts/default_address.html' with default_billing_address=default_billing_address default_shipping_address=default_shipping_address %}#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
        </div>
        <div class="box-account box-address">
            <div class="box-head">
                <h3>Address Book</h3>
                <a href="{% url 'cart:account_address' %}">Manage Addresses</a>
            </div>
            {% include 'frontend/pages/accounts/parts/default_address.html' with default_billing_address=default_billing_address default_shipping_address=default_shipping_address %}
        </div>
        <div class="box-account box-recent">
            <div class="box-head">
                <h3>Recent Orders</h3>
                <a href="{% url 'cart:account_orders' %}">View All</a>
            </div>
            <table class="table table-responsive data-table" id="my-orders-table">
                <colgroup>
                    <col width="1">
                    <col width="1">
                    <col>
                    <col width="1">
                    <col width="1">
                    <col width="1">
                </colgroup>
                <thead>
                <tr class="first last">
                    <th>Order #</th>
                    <th>Date</th>
                    <th>Ship To</th>
                    <th><span class="nobr">Order Total</span></th>
                    <th>Status</th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                <tbody>
                {% if orders %}
                    {% for order in orders %}
                        <tr class="{% if forloop.first %}first{% endif %}{% if forloop.last %}last{% endif %} odd">
                            <td>{{ order.get_order_id }}</td>
                            <td><span class="nobr">{{ order.created_at|date:"m/d/Y" }}</span></td>
                            <td>{{ order.get_customer_name }}</td>
                            <td><span class="price">${{ order.grand_total|floatformat:2 }}</span></td>
                            <td><em>{{ order.status|capfirst }}</em></td>
                            <td class="a-center last">
                                <span class="nobr"><a href="{% url 'cart:account_order_view' order.id %}">View Order</a></span>
                            </td>
                        </tr>

{#                <tr class="first odd">#}
{#                    <td>100030482</td>#}
{#                    <td><span class="nobr">4/30/2020</span></td>#}
{#                    <td>Mainul Hasan</td>#}
{#                    <td><span class="price">$47.95</span></td>#}
{#                    <td><em>Complete</em></td>#}
{#                    <td class="a-center last">#}
{#                        <span class="nobr">#}
{#                        <a href="http://shop.johnamico.dev2.mvisolutions.com/sales/order/view/order_id/29225/">View Order</a>#}
{#                                                </span>#}
{#                    </td>#}
{#                </tr>#}

                    {% endfor %}
                {% else %}
                    <tr class="no-order">
                        <td colspan="6">No orders found</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

project/apps/cart/templates/frontend/pages/accounts/order_list.html
{% extends 'frontend/pages/accounts/base.html' %}
{% load static %}


{% block head_style_block %}
{#    {{ block.super }}#}
    {% include 'frontend/parts/page/accounts/base/style.html' %}
{% endblock %}

{% block content %}
    <div class="dashboard">
        <div class="page-title">
            <h1>My Orders</h1>
        </div>
{#        <div class="welcome-msg">#}
{#            <p class="hello"><strong>Hello, Mainul Hasan!</strong></p>#}
{#            <p>From your My Account Dashboard you have the ability to view a snapshot of your recent account activity#}
{#                and update your account information. Select a link below to view or edit information.</p>#}
{#        </div>#}
        <div class="box-account box-recent">
            <table class="data-table" id="my-orders-table">
                <colgroup>
                    <col width="1">
                    <col width="1">
                    <col>
                    <col width="1">
                    <col width="1">
                    <col width="1">
                </colgroup>
                <thead>
                <tr class="first last">
                    <th>Order #</th>
                    <th>Date</th>
                    <th>Ship To</th>
                    <th><span class="nobr">Order Total</span></th>
                    <th>Status</th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                <tbody>
                {% if orders %}
                    {% for order in orders %}
                        <tr class="{% if forloop.first %}first{% endif %}{% if forloop.last %}last{% endif %} odd">
                            <td>{{ order.get_order_id }}</td>
                            <td><span class="nobr">{{ order.created_at|date:"m/d/Y" }}</span></td>
                            <td>{{ order.get_customer_name }}</td>
                            <td><span class="price">${{ order.grand_total|floatformat:2 }}</span></td>
                            <td><em>{{ order.status|capfirst }}</em></td>
                            <td class="a-center last">
                                <span class="nobr"><a href="{% url 'cart:account_order_view' order.id %}">View Order</a></span>
                            </td>
                        </tr>

{#                <tr class="first odd">#}
{#                    <td>100030482</td>#}
{#                    <td><span class="nobr">4/30/2020</span></td>#}
{#                    <td>Mainul Hasan</td>#}
{#                    <td><span class="price">$47.95</span></td>#}
{#                    <td><em>Complete</em></td>#}
{#                    <td class="a-center last">#}
{#                        <span class="nobr">#}
{#                        <a href="http://shop.johnamico.dev2.mvisolutions.com/sales/order/view/order_id/29225/">View Order</a>#}
{#                                                </span>#}
{#                    </td>#}
{#                </tr>#}

                    {% endfor %}
                {% else %}
                    <tr class="no-order">
                        <td colspan="6">No orders found</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}